// Code generated by go-swagger; DO NOT EDIT.

package album

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go-api-gin-swagger/client/models"
)

// GetAlbAlbumsReader is a Reader for the GetAlbAlbums structure.
type GetAlbAlbumsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAlbAlbumsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAlbAlbumsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAlbAlbumsOK creates a GetAlbAlbumsOK with default headers values
func NewGetAlbAlbumsOK() *GetAlbAlbumsOK {
	return &GetAlbAlbumsOK{}
}

/* GetAlbAlbumsOK describes a response with status code 200, with default header values.

OK
*/
type GetAlbAlbumsOK struct {
	Payload []*models.ModelAlbum
}

func (o *GetAlbAlbumsOK) Error() string {
	return fmt.Sprintf("[GET /alb/albums][%d] getAlbAlbumsOK  %+v", 200, o.Payload)
}
func (o *GetAlbAlbumsOK) GetPayload() []*models.ModelAlbum {
	return o.Payload
}

func (o *GetAlbAlbumsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
