// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelAlbum model album
//
// swagger:model model.Album
type ModelAlbum struct {

	// artist
	Artist string `json:"artist,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this model album
func (m *ModelAlbum) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model album based on context it is used
func (m *ModelAlbum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelAlbum) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelAlbum) UnmarshalBinary(b []byte) error {
	var res ModelAlbum
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
