// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go-api-gin-swagger/client/models"
)

// GetAlbAlbumsIDReader is a Reader for the GetAlbAlbumsID structure.
type GetAlbAlbumsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAlbAlbumsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAlbAlbumsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAlbAlbumsIDOK creates a GetAlbAlbumsIDOK with default headers values
func NewGetAlbAlbumsIDOK() *GetAlbAlbumsIDOK {
	return &GetAlbAlbumsIDOK{}
}

/* GetAlbAlbumsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetAlbAlbumsIDOK struct {
	Payload *models.ModelAlbum
}

func (o *GetAlbAlbumsIDOK) Error() string {
	return fmt.Sprintf("[GET /alb/albums/{id}][%d] getAlbAlbumsIdOK  %+v", 200, o.Payload)
}
func (o *GetAlbAlbumsIDOK) GetPayload() *models.ModelAlbum {
	return o.Payload
}

func (o *GetAlbAlbumsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelAlbum)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
