// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"go-api-gin-swagger/client/client/albums"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationAlbumsGetAlbAlbumsIDCmd returns a cmd to handle operation getAlbAlbumsId
func makeOperationAlbumsGetAlbAlbumsIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetAlbAlbumsID",
		Short: `get string by ID`,
		RunE:  runOperationAlbumsGetAlbAlbumsID,
	}

	if err := registerOperationAlbumsGetAlbAlbumsIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationAlbumsGetAlbAlbumsID uses cmd flags to call endpoint api
func runOperationAlbumsGetAlbAlbumsID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := albums.NewGetAlbAlbumsIDParams()
	if err, _ := retrieveOperationAlbumsGetAlbAlbumsIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationAlbumsGetAlbAlbumsIDResult(appCli.Albums.GetAlbAlbumsID(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationAlbumsGetAlbAlbumsIDParamFlags registers all flags needed to fill params
func registerOperationAlbumsGetAlbAlbumsIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationAlbumsGetAlbAlbumsIDIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationAlbumsGetAlbAlbumsIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Album ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationAlbumsGetAlbAlbumsIDIDFlag(m *albums.GetAlbAlbumsIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationAlbumsGetAlbAlbumsIDResult parses request result and return the string content
func parseOperationAlbumsGetAlbAlbumsIDResult(resp0 *albums.GetAlbAlbumsIDOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*albums.GetAlbAlbumsIDOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
