// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"go-api-gin-swagger/client/client/example"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationExampleGetExampleHelloworldCmd returns a cmd to handle operation getExampleHelloworld
func makeOperationExampleGetExampleHelloworldCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetExampleHelloworld",
		Short: `do ping`,
		RunE:  runOperationExampleGetExampleHelloworld,
	}

	if err := registerOperationExampleGetExampleHelloworldParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationExampleGetExampleHelloworld uses cmd flags to call endpoint api
func runOperationExampleGetExampleHelloworld(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := example.NewGetExampleHelloworldParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationExampleGetExampleHelloworldResult(appCli.Example.GetExampleHelloworld(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationExampleGetExampleHelloworldParamFlags registers all flags needed to fill params
func registerOperationExampleGetExampleHelloworldParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationExampleGetExampleHelloworldResult parses request result and return the string content
func parseOperationExampleGetExampleHelloworldResult(resp0 *example.GetExampleHelloworldOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*example.GetExampleHelloworldOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr := fmt.Sprintf("%v", resp0.Payload)
		return string(msgStr), nil
	}

	return "", nil
}
