{
 "title": "GIN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "go_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "go_info", "legendFormat": "{{instance}} {{version}}" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "gin_gin_request_duration_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    { "expr": "gin_gin_request_duration_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gin_gin_request_duration_bucket",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "gin_gin_request_duration_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gin_gin_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "targets": [
    { "expr": "gin_gin_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}